### ISSUE TITLE
Referrals do not get the sats

### ISSUE THREAD

**Issue by Darth-Coin** [stackernews/stacker.news#1002]
**Description**
When new users join from invitation links, they get errors and sats are not delivered.

**Steps to Reproduce**
I sent an invitation link with 1000 sats. User log in from that link, with LN-auth/nostr and first thing is getting this error

Then refreshing the page, is showing the new account created with 0 sats balance.

In my balance / invitation report, the sats are not taken and the invitation is not "consumed".

**Expected behavior**
It should debit the sats into his account and take them from my account.

**Screenshots**
![image](https://github.com/stackernews/stacker.news/assets/56997124/5305f206-e31f-477b-84d4-3a5ef7af4bf7)

**Logs**
If applicable, add your browsers console logs.

**Environment:**
 - Device: desktop
 - OS: Linus
 - Browser Brave

**Additional context**
I've sent him 100 sats to his bio, just to test his account and he got this error:
![image](https://github.com/stackernews/stacker.news/assets/56997124/a6bb44d9-b375-4ba8-8118-3dc9e37fec7a)

Also received 90 sats not 100.
I though posting his bio is free.
Also as a new user is charged 1000 sats for a first post. So I had to send more sats through SN PM to be able to post 1st time, without the sats from invitation.

User wasn't very impressed by the onboarding process with so many errors.

**Comment by ekzyis** [comment]
> I sent an invitation link with 1000 sats. User log in from that link, with LN-auth/nostr and first thing is getting this error
>
> Then refreshing the page, is showing the new account created with 0 sats balance.
>
> In my balance / invitation report, the sats are not taken and the invitation is not "consumed".

This is unfortunately a bug with LN-auth/nostr that we had for a long time. See #375 and #679. We need to fix that but  we're probably going to rework our whole referral/invite process anyway.

> I've sent him 100 sats to his bio, just to test his account and he got this error:

The push service error happens if the Google services for push messaging are not enabled in the privacy and security settings of Brave. Brave does not provide an own push service and I assume Brave disabled Google services by default for privacy reasons.

![2024-03-30-132953_972x224_scrot](https://github.com/stackernews/stacker.news/assets/27162016/3f2e6de1-498b-46e6-bdad-b53dd6046d73)

_we should probably mention this in the error message in some way since this isn't clear from the error message and can't expect stackers to research their own (browser-specific) errors_

> Also received 90 sats not 100.

Did you zap his bio or send him via LN address? If you zap his bio, the regular 10% sybil fee applies. [See FAQ](https://stacker.news/faq#do-zaps-help-content-rank-higher):

> To make this feature sybil resistant, SN now takes 10% of zaps and re-distributes them to the SN community as part of the daily rewards.

> I though posting his bio is free.

No, if you have sats in your custodial wallet, it costs 1 sat. If not, it's free but it's marked as a freebie and only stackers with greeter mode enabled in their settings will see it (until someone zaps it).

> Also as a new user is charged 1000 sats for a first post. So I had to send more sats through SN PM to be able to post 1st time, without the sats from invitation.

[I see he posted in ~bitcoin](https://stacker.news/items/486283). It costs 100 sats there. It would only cost him 1000 sats if he posted something before within 10 minutes. For every post within 10m, the fees are raised by 10x.

I see in our logs though that it only cost him 100 sats since his bio was an hour earlier and not within 10m. So I think he waited and did not really pay 1k sats but was spooked by the initial fee?

[That also confused your previous invitee and we should exclude bios from this fee calculation.](https://stacker.news/items/457126?commentId=457390)

> User wasn't very impressed by the onboarding process with so many errors.

Sorry to hear that but understandable :/

**Comment by Darth-Coin** [comment]
Ah OK now I understand. Make sense to take a cut of 10%.
No problem, I thought it is a separate bug, but is OK.
Yeah I sent him more sats through SN Ln address so he can have the credit I promise him before joining and use it to make his first post and also have enough to zap, in case is needed.

These invitation links are very good for these cases to give to somebody enough sats to start. Later they can do whatever they want, deposit more or just earn. Is not my problem anymore.

**Comment by JavierRSobrino** [comment]
Problem with push notifications solved after enabling Google push service. Anyway I'm not confident about Google knowing I'm receiving notifications from Stacker, it's probably a privacy breach.

 The bug with LN-auth/nostr I hope you can solve it.

**Comment by ekzyis** [comment]
> Anyway I'm not confident about Google knowing I'm receiving notifications from Stacker, it's probably a privacy breach.

It probably is indeed, the content is encrypted but they might be able to tell that you're receiving notifications from us.

It's unfortunately out of our control, browsers decide which push service they use.
