### ISSUE TITLE
Unable to connect CLN node using clnrest for withdrawal over Tor

### ISSUE THREAD

**Issue by s373nZ** [stackernews/stacker.news#1107]
*Note: this template is meant to help you report the bug so that we can fix it faster, ie not all of these sections are required*

**Description**
I've tried to hook up my node using the built-in clnrest plugin for autowithdrawal over Tor. Haven't been able to get this to work yet. I've verified that it works accessing the node's Swagger page on that port over Tor and simulated the request parameters I've found in in the code so I think my node is fine. StackerNews logs give the following:
```
20m	[cln]	ERROR	failed to attach wallet
1m	[cln]	ERROR	could not connect to CLN: request to https://[redacted].onion:3010/v1/invoice failed, reason: getaddrinfo ENOTFOUND [redacted].onion
1m	[cln]	ERROR	failed to attach wallet
```

My guess is that hostname resolution over Tor isn't working quite right.

**Steps to Reproduce**
Try to connect a CLN node over Tor using the built-in clnrest plugin.

**Expected behavior**
Wallet would connect and issue invoice for autowithdraw.

**Screenshots**
Prefer not to provide screenshots at this time -- let me know if necessary.

**Logs**
Provided with descrtiption.

**Environment:**
If you only experience the issue on certain devices or browsers, provide that info.

I don't feel this is applicable right now.

**Additional context**

I can add more information if necessary. I've taken a quick look at the code and currently wondering how [createInvoice](https://github.com/stackernews/stacker.news/blob/13eda4c1204acd5b54235d38ba9710336c04ffdc/lib/cln.js#L5) detects Tor traffic and routes accordingly. I can keep looking at it or provide more information, but short on time ATM and wanted to write up an issue in case something obvious is being overlooked.

**Comment by huumn** [comment]
Thanks for the detailed report!

**Comment by ekzyis** [comment]
I don't think this is related to the shown error since I would expect something different than `getaddrinfo ENOTFOUND` then but I think this line would also make problems when trying to connect to a CLN node over Tor:

https://github.com/stackernews/stacker.news/blob/13eda4c1204acd5b54235d38ba9710336c04ffdc/lib/cln.js#L7

For example, http://dreadytofatroptsdj6io7l3xptbet6onoyno2yv7jicoxknyazubrad.onion/ works but https://dreadytofatroptsdj6io7l3xptbet6onoyno2yv7jicoxknyazubrad.onion/ does not work with `NS_ERROR_CONNECTION_REFUSED`. I also don't see any mention of HTTPS in the [Tor docs of CLN](https://docs.corelightning.org/docs/tor).

My knowledge about Tor internals is lacking but my educated guess would be that onion URLs usually don't use HTTPS since onion routing already provides encryption[^1]. So I think we would also need this patch, independent of the `getaddrinfo ENOTFOUND`:

```diff
diff --git a/lib/cln.js b/lib/cln.js
index 6b06ae99..191c27bc 100644
--- a/lib/cln.js
+++ b/lib/cln.js
@@ -4,7 +4,9 @@ import crypto from 'crypto'

 export const createInvoice = async ({ socket, rune, cert, label, description, msats, expiry }) => {
   const agent = cert ? new https.Agent({ ca: Buffer.from(cert, 'base64') }) : undefined
-  const url = 'https://' + socket + '/v1/invoice'
+  let protocol = 'https://'
+  if (socket.endsWith('.onion')) protocol = 'http://'
+  const url = protocol + socket + '/v1/invoice'
   const res = await fetch(url, {
     method: 'POST',
     headers: {
```

[^1]: but not authentication

**Comment by huumn** [comment]
Yep, that's the problem! The tor proxy isn't used when `https` is specified.

**Comment by ekzyis** [comment]
Oh, lol, well, that explains the error.

**Comment by ekzyis** [comment]
Mhh, I just tested out the patch and it breaks with `could not connect to CLN: Protocol "http:" not supported. Expected "https:"` because we use an HTTPS agent when a certificate is provided. I could do this:

```diff
diff --git a/lib/cln.js b/lib/cln.js
index 191c27bc..45fa418b 100644
--- a/lib/cln.js
+++ b/lib/cln.js
@@ -3,10 +3,11 @@ import https from 'https'
 import crypto from 'crypto'

 export const createInvoice = async ({ socket, rune, cert, label, description, msats, expiry }) => {
-  const agent = cert ? new https.Agent({ ca: Buffer.from(cert, 'base64') }) : undefined
-  let protocol = 'https://'
-  if (socket.endsWith('.onion')) protocol = 'http://'
-  const url = protocol + socket + '/v1/invoice'
+  let protocol = 'https:'
+  // Tor proxy only used if HTTP is used
+  if (/\.onion(:\d+)?$/.test(socket)) protocol = 'http:'
+  const agent = protocol === 'https:' && cert ? new https.Agent({ ca: Buffer.from(cert, 'base64') }) : undefined
+  const url = protocol + '//' + socket + '/v1/invoice'
   const res = await fetch(url, {
     method: 'POST',
     headers: {
```

but this would force HTTP for clnrest over Tor which will also not work if HTTPS is expected by clnrest. [I noticed that the protocol can be specified using `--clnrest-protocol` and HTTPS is the default](https://docs.corelightning.org/docs/rest#configuration).

Therefore, I think the proper fix would be to enable the Tor proxy if the hostname ends with `.onion` so HTTP and HTTPS would work so stacker don't have to use HTTP for us. As @huumn mentioned, the Tor proxy is only used for HTTP since `HTTPTunnelPort` is used in tor.config:

https://github.com/stackernews/stacker.news/blob/13eda4c1204acd5b54235d38ba9710336c04ffdc/.ebextensions/tor.config#L8-L18

I am not sure yet if that's possible via torrc though but I will find out.

**Comment by huumn** [comment]
We can't conditionally enable the tor proxy. They are env vars that we set. See: https://www.golinuxcloud.com/set-up-proxy-http-proxy-environment-variable/

So we'd end up passing all of our traffic through the proxy. I was hesitant to do this before, but I can't remember why exactly.

**Comment by s373nZ** [comment]
Would it be possible to conditionally set a [custom agent](https://github.com/node-fetch/node-fetch?tab=readme-ov-file#custom-agent) in the `fetch` call using a class like [this](https://www.tabnine.com/code/javascript/functions/http/Agent?snippet=5f621d0c43564f2b5cc7e89b)?

Or are you saying the environment variable setup would override this approach?

**Comment by huumn** [comment]
Something like that might work!

**Comment by huumn** [comment]
@s373nZ do you have a lightning address I can send sats to. If not, can you send me a bolt11?

**Comment by s373nZ** [comment]
@huumn Sure thing :smile:! se7enz@minibits.cash -- if that has issues, LMK. Thank you kindly!

Is this already live now as it's been merged into `master`?

**Comment by s373nZ** [comment]
Phew. I tested it out again immediately and was hoping the results weren't suggesting the proxy change had no impact. I'll keep an eye on that footer, thanks.

**Comment by ekzyis** [comment]
It's deployed now. Does it work for you now?

**Comment by s373nZ** [comment]
@ekzyis I just tested again. It looks like I'm able to connect over the proxy now, but my use case has a new error:
```
1s	[cln]	ERROR	could not connect to CLN: request to http://[redacted]:3010/v1/invoice failed, reason: socket hang up
0s	[cln]	ERROR	failed to attach wallet
```

It looks like SN is now trying to force an `HTTP` connection? I still have my `clnrest-protocol` set to `https`. Sorry - this might be an edge case...

BTW - thank you for the generous award, @huumn -- I wasn't expecting that. Very much appreciated.

**Comment by ekzyis** [comment]
> It looks like SN is now trying to force an `HTTP` connection

Our Tor proxy listens for HTTP so we're only using HTTP to resolve the onion address and get a socket over which the actual connection will be established. The actual connection can be HTTP or HTTPS since Tor already encrypts packets. So we're trying to make HTTPS and HTTP over Tor work.

> I still have my `clnrest-protocol` set to `https`. Sorry - this might be an edge case...

Nah, you're good. I don't think that's an edge case since CLNRest defaults to HTTPS. Anyone who uses Tor will probably encounter this bug.

Just to make sure: Did you set a certificate? If you don't, we indeed force HTTP for Tor. But [reading this](https://stackoverflow.com/a/27835115), `socket hang up` might be due to timeouts since Tor is known to be slow?

I will setup my own CLN node on Tor and test this properly.

**Comment by s373nZ** [comment]
You were right - I wasn't setting the certificate :/ After digging around in the CLN documentation and trying to `base64` encode all of the various certificates it generates, I finally got to the point where I'm getting this error using the value from `openssl base64 -in ca.pem` and reformatting it for the input field:

```
0s	[cln]	ERROR	could not connect to CLN: request to https://[redacted].onion:3010/v1/invoice failed, reason: Hostname/IP does not match certificate's altnames: Host: [redacted].onion. is not in the cert's altnames: DNS:cln, DNS:localhost, IP Address:127.0.0.1
0s	[cln]	ERROR	failed to attach wallet
```

The cert isn't valid for the Tor hostname. Obviously this doesn't seem to be an issue with your SN implementation. I probably need to educate myself further from the CLN docs / code and refine my familiarity with SSL to make sure using the CA is expected here -- but so far it was the only one that didn't fail the SSL check outright with:

```
4m	[cln]	ERROR	could not connect to CLN: request to https://[redacted].onion:3010/v1/invoice failed, reason: unable to verify the first certificate
```

Out of time for today and will have to look later. Let me know if you have any pointers. Thanks!

**Comment by ekzyis** [comment]
That's very useful information. thanks! So this means the proxy works and we can reach your node now but the TLS connection now fails.

I have encountered this error before while implementing #1042 since CLN was running inside docker. I forgot that this will be an issue for stackers, too.

Fortunately, CLN is aware of this and they provided [this documentation](https://docs.corelightning.org/docs/grpc#generating-custom-certificates-optional) which helped me. It's listed under the gRPC documentation but it also applies to the TLS certificates for the REST API.

Therefore, can you try this:

1. Generate server private key

```
$ openssl genrsa -out server-key.pem 2048
```

2. Generate certificate signature request. This will ask you a few questions. Provide your onion address as common name.

```
$ openssl req -key server-key.pem -new -out server.csr
```

3. Sign certificate

```
$ openssl x509 -req -CA ca.pem -CAkey ca-key.pem \
  -in server.csr \
  -out server.pem \
  -days 365 -CAcreateserial
```

4. Move `server.pem` and `server-key.pem` into lightning directory and restart node:

> This will finally create the server.pem file, signed by the CA, allowing you to access the node through its real domain name. You can now move server.pem and server-key.pem into the lightning directory, and they should be picked up during the start.

We can also consider disabling verifying TLS signatures for Tor connections. I am still not sure if or how much TLS over Tor makes sense.

For (our) reference, this is apparently how Alby connects to Tor nodes. They have a [companion app](https://github.com/getAlby/alby-companion-rs) written in Rust. [They seem to ignore invalid certificates for Tor](https://github.com/getAlby/alby-companion-rs/blob/f21499a25e4010320072438a8c14bfe3061f04e1/src/requests.rs#L71-L73).

**Comment by s373nZ** [comment]
@ekzyis Thanks for all the detailed information. It certainly helped. As an update -- I spent several hours today trying to get this working, but ultimately haven't gotten there yet. I followed your instructions (and those of the CLN docs) multiple times in different contexts, but I'm still getting the same error. Strangely, my existing CLN certificates seem to be located in the `.lightning/bitcoin` directory -- I don't know if this is an effect of setting up initially with [Raspibolt](https://raspibolt.org/guide/bonus/lightning/cln.html), or CLN's default. I tried:
1. Overwriting the existing CLN `server.pem` and `server-key.pem` with the output from the above.
2. Placing the new `server.pem` and `server-key.pem` into the `~/.lightning` data directory thinking that CLN should pick it up and override it.
3. Finally just set the `clnrest-certs` configuration value to a new directory, which generated a whole new set of certificates, and performed the instructions inside that directory.

Two notes:
* The `ca.pem` I'm using for the above commands is that generated automatically by CLN itself. If this process requires a completely custom CA -- that's a whole different step change for my TLS experience level.
* The CLN logs show the following error, which initial [Google searches](https://stackoverflow.com/questions/77136065/unexpected-eof-while-reading-when-using-requests-in-python-eof-occurred-in-viol) indicate is related to `openssl` v3 (shipped with Ubuntu 23.10) and is generally addressed by disabling certificate validation:
```
May 09 18:57:38 : ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1002)
May 09 18:57:38 : 2024-05-09T16:57:38Z <Greenlet at 0x7f1fa61a0400: _handle_and_close_when_done(<bound method StreamServer.wrap_socket_and_handle , <bound method StreamServer.do_close of <PyWSGIServ, (<gevent._socket3.socket [closed] at 0x7f1fa6bc232)> failed with SSLEOFError
May 09 19:08:05 : Traceback (most recent call last):
May 09 19:08:05 :   File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
May 09 19:08:05 :   File "/home/lightningd/.local/lib/python3.11/site-packages/gevent/baseserver.py", line 34, in _handle_and_close_when_done
May 09 19:08:05 :     return handle(*args_tuple)
May 09 19:08:05 :            ^^^^^^^^^^^^^^^^^^^
May 09 19:08:05 :   File "/home/lightningd/.local/lib/python3.11/site-packages/gevent/server.py", line 209, in wrap_socket_and_handle
May 09 19:08:05 :     with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
May 09 19:08:05 :                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 09 19:08:05 :   File "/home/lightningd/.local/lib/python3.11/site-packages/gevent/ssl.py", line 121, in wrap_socket
May 09 19:08:05 :     return self.sslsocket_class(
May 09 19:08:05 :            ^^^^^^^^^^^^^^^^^^^^^
May 09 19:08:05 :   File "/home/lightningd/.local/lib/python3.11/site-packages/gevent/ssl.py", line 319, in __init__
May 09 19:08:05 :     raise x
May 09 19:08:05 :   File "/home/lightningd/.local/lib/python3.11/site-packages/gevent/ssl.py", line 315, in __init__
May 09 19:08:05 :     self.do_handshake()
May 09 19:08:05 :   File "/home/lightningd/.local/lib/python3.11/site-packages/gevent/ssl.py", line 673, in do_handshake
May 09 19:08:05 :     self._sslobj.do_handshake()
```

Was your Docker setup using OpenSSL v3 by chance?

I'd like to offer my two sats on the bigger picture. While I *really* appreciate the flexibility that the existing UI implicates that would allow masochists like myself to go for certificate validation over Tor if they so wanted, I think the most reasonable default is to disable it as a default for onion addresses. Even if I was doing this for a client, I would probably settle for `http` over Tor, which is quite common if the security standards of Raspibolt and Minibolt are anything to go by. A UI suggestion would be to add a checkbox if an `.onion` URL is detected named "Use HTTPS".
* If the box is checked, request is sent over Tor without cert validation.
* If the box is checked and the user also adds a CA, then enforce validation as well.

Just my thought -- might be too many cases to maintain. Anyway, I'd love to finally figure this out regardless. If you see any mistakes, please let me know. Otherwise I'll try again a bit later.

Thanks again for the support!

**Comment by ekzyis** [comment]
Did you try disabling HTTPS via `--clnrest-protocol http`? Would be nice to know if that works. 

I'll reply to the rest later, thanks again for the detailed answer :)

**Comment by ekzyis** [comment]
> Strangely, my existing CLN certificates seem to be located in the .lightning/bitcoin directory -- I don't know if this is an effect of setting up initially with [Raspibolt](https://raspibolt.org/guide/bonus/lightning/cln.html), or CLN's default.

It's CLN's default, configuration is split by the network you use. "bitcoin" means mainnet. So you're fine.

> The ca.pem I'm using for the above commands is that generated automatically by CLN itself. If this process requires a completely custom CA -- that's a whole different step change for my TLS experience level.

Yes, that's good! No custom CA is required. The steps are about generating a new server certificate signed by the existing CA.

> Was your Docker setup using OpenSSL v3 by chance?

Mhh, not sure. I was using [this image](https://hub.docker.com/layers/elementsproject/lightningd/v23.08/images/sha256-7642a96a22fa9f4265482896b94bf8f429d58c48e4f739560255dfa114f56318) and I can't tell which distro this image is using on first glance. When do these errors show up? During startup? Or when we try to connect to your node? And only when you use the custom certificates or also when you use the automatically generated certificates?

> I'd like to offer my two sats on the bigger picture. While I really appreciate the flexibility that the existing UI implicates that would allow masochists like myself to go for certificate validation over Tor if they so wanted, I think the most reasonable default is to disable it as a default for onion addresses. Even if I was doing this for a client, I would probably settle for http over Tor, which is quite common if the security standards of Raspibolt and Minibolt are anything to go by. A UI suggestion would be to add a checkbox if an .onion URL is detected named "Use HTTPS".
> 
> If the box is unchecked, the request is sent over Tor using HTTP.
If the box is checked, request is sent over Tor using HTTPS without cert validation.
If the box is checked and the user also adds a CA, then enforce validation as well.
Just my thought -- might be too many cases to maintain. Anyway, I'd love to finally figure this out regardless. If you see any mistakes, please let me know. Otherwise I'll try again a bit later.

I agree, I also think it makes sense to disable certification validation over Tor by default. I'll push a PR that sets [`rejectUnauthorized`](https://nodejs.org/api/tls.html#tlsconnectoptions-callback) to false for Tor in a bit.

I have to think more about opt-in certificate validation for Tor though.

**Comment by s373nZ** [comment]
@ekzyis Thanks again for the feedback.

> I was using [this image](https://hub.docker.com/layers/elementsproject/lightningd/v23.08/images/sha256-7642a96a22fa9f4265482896b94bf8f429d58c48e4f739560255dfa114f56318) and I can't tell which distro this image is using on first glance.

I tested the CLN Docker image you linked and it is indeed created with OpenSSL version `1.1.1`.

> When do these errors show up? During startup? Or when we try to connect to your node?

The errors show up in my CLN log when SN tries to connect to my node.

> Did you try disabling HTTPS via --clnrest-protocol http? Would be nice to know if that works.

I just tried this and was able to connect successfully! Autowithdraw kicks in, creates an invoice and tries to pay, but in my case it hangs in `pending`, unable to find a route. I bumped the percentage up from 1 to 7, so I'll see if that helps. Unfortunately, I had to also change my local RTL management tool to communicate over `http` on `localhost` to continue to work. Only a minor nuisance, but still.

> And only when you use the custom certificates or also when you use the automatically generated certificates?

I have mangled my certs a little bit with the experiments and would have to switch back to `https` as well as restore backup certs in order to test this. I can try, but want to give autowithdraw over `http` some time to see if it ends up working. I can do this, though, if you're curious about it.

Hope this is useful, somehow. At least there are signs of success with `http` over Tor :)

**Comment by ekzyis** [comment]
> I just tried this and was able to connect successfully!

Nice! When #1165 is deployed, you should be able to continue to use `--clnrest-protocol https` (which is the default).

> Autowithdraw kicks in, creates an invoice and tries to pay, but in my case it hangs in pending, unable to find a route. I bumped the percentage up from 1 to 7, so I'll see if that helps.

Good idea, this should help

> I have mangled my certs a little bit with the experiments and would have to switch back to https as well as restore backup certs in order to test this. I can try, but want to give autowithdraw over http some time to see if it ends up working. I can do this, though, if you're curious about it.

Don't worry about it, I have high hopes for #1165 now

> Hope this is useful, somehow. At least there are signs of success with http over Tor :)

Very useful!

**Comment by ekzyis** [comment]
Hey, we did a [release](https://stacker.news/items/540701) today which includes to no longer validate certificates on Tor in production (#1165). You should be able to use HTTPS over Tor now.

**Comment by s373nZ** [comment]
I switch back to SSL for clnrest and SN connected to my node perfectly. Works as discussed. Thanks :D
