### ISSUE TITLE
LNC failing in prod due to CSP

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1116]
https://stacker.news/items/520971/r/k00b?commentId=522044

> Getting this error:
> invalid config: CompileError: Refused to create a WebAssembly object because 'unsafe-eval' or 'wasm-unsafe-eval' is not an allowed source of script in the following Content Security Policy directive:

**Comment by ekzyis** [comment]
Mhh, the last time we received CSP reports from stackers because NWC didn't work for them it was a false alarm. It ended up being a missing space. See https://github.com/stackernews/stacker.news/issues/821 and https://github.com/stackernews/stacker.news/pull/845.

But I think the context is different here since in the previous case, it worked with some NWC wallets. If it's CSP here, it should fail for all stackers since even old browsers which don't support CSP Level 3 (`strict-dynamic` and nonces) should still respect our CSP and fallback to `unsafe-inline` and thus run into this error.

So would be nice to know if LNC works for anyone in prod

**Comment by huumn** [comment]
I intended to get mine setup today, but as is my fashion, I gave myself too much to do.
