### ISSUE TITLE
Lack of msats support from LNURL providers 

### ISSUE THREAD

**Issue by kepford** [stackernews/stacker.news#1303]
**Description**

My SN wallet is above the limit I have set. Went to the attach wallet config page for it and I see many log messages like this.

`13m	[lnAddr]	error	creating invoice for SN: autowithdrawal failed: Error: invoice has incorrect amount`

My wallet is a lightning address type of wallet. This seems to have started about 19 hours ago.

**Steps to Reproduce**

Set up an Alby wallet with lightning address and set your wallet limit. Now receive sats above the limit.

**Expected behavior**

**Comment by huumn** [comment]
I changed that code as part of the release. Thanks for making an issue!

**Comment by huumn** [comment]
Looks like even though the spec requires specifying amounts in msats, most implementations want the amount round to the nearest sat.

**Comment by kepford** [comment]
Ah! That error makes sense then. Maybe this should be reported to Alby

**Comment by huumn** [comment]
Looks like a lot of lightning providers don't like msats though. Natalia reported hers as:

`creating invoice for SN: autowithdrawal failed: Error: Millisatoshi amount is not supported, please send a value in full sats.`

Ahrg, without this changing, it means for p2p zaps the receiver can't receive all the millisats they're owed.

**Comment by kepford** [comment]
> p2p zaps lightning address receivers can't receive all the millisats they're owed.

We so early  ™

**Comment by ekzyis** [comment]
I reached out to Alby

**Comment by ekzyis** [comment]
> Looks like a lot of lightning address providers don't like msats though

@bumi from Alby also mentioned this. Looks like we also have to round our number or risk invoices over LNURL failing. Or we could catch this error, round down and retry so this only affects users with such LNURL providers. Ideally, we would let the user know that their LNURL provider does not support msats so they might receive receive a little less than possible of each zap.

**Comment by huumn** [comment]
The problem is that for p2p we assume the invoice hasn’t been rounded to compute what the zapper will pay, eg ‘inv.msats * 10 / 9’. I was going to try to get fancy with math but it’s probably better to just be explicit about forward amounts and what the zapper will pay when doing p2p.

Also its weird to hear “the spec is what we implemented not what it says” over and over.

At the very least, providers should not be rounding what’s requested. It’s like someone orders an apple and you give the customer an orange painted red.
