### ISSUE TITLE
Rumble video embed like what was added for Youtube

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#134]
Rumble is a video hosting network that is gaining in popularity, not just because of its monetization feature  (i.e., payouts to creators) but  but also because it is the relatively common destination for those who suffered from having their Youtube account terminated (censorship).  

This request is to add support for a Post for a link that is a Rumble video to include either the javascript embed or the iframe embed so that the video can be played within the SN post, similarly to how there is now Youtube embed, and Twitter embed support in SN (see Issue https://github.com/stackernews/stacker.news/issues/9).

**Comment by cointastical** [comment]
There's also a similar, related, issue: #107 (for embed of Peertube)

**Comment by cointastical** [comment]
This feature request was discussed on SN, [Item #18804](https://stacker.news/items/18804).

**Comment by benalleng** [comment]
So unfortunately because of the way Rumbles revenue sharing works pasting the link in the top url and getting an embed is not possible like is done in [Item #18804](https://stacker.news/items/18804) but you can copy the embed link at the bottom of the video

![image](https://github.com/stackernews/stacker.news/assets/108441023/5bda7d31-6284-4913-883a-3d66793de9ff)

https://rumble.com/embed/v17j3tt/?pub=3fid3f vs https://rumble.com/v1a59rb-rumble-basics-how-to-embed-your-video.html the first being what can be embedded. 

I was able to create a branch that tests embeds for rumble and I would like to eventually embed all the sites but lets start with the POC first in

**Comment by huumn** [comment]
@benalleng was struggling to add the hack approach in #981 and I think decided to work on something else.

**Comment by benalleng** [comment]
It had to do with this need for a reverse proxy here https://github.com/stackernews/stacker.news/pull/981#discussion_r1553620387. We had come to the conclusion that the embed link doesn't really have a ton of value if no-one ever uses it.

**Comment by benalleng** [comment]
I think you can totally try to get it the rest of the way! This PR does include working support for peertube links and its forks __ilike bitcoin.tv__. If nothing else you can just split that code off and close #107

**Comment by tsmith123** [comment]
Thanks for the info. I'll try and take a look tomorrow.
