### ISSUE TITLE
Easy/fun UI for deciding how many sats to tip

### ISSUE THREAD

**Issue by philosopher-phaedrus** [stackernews/stacker.news#146]
Tapping the bolt icon is awesome, super easy. I love it. It feels good!

Often I wanna tip more (in fact most of the time), but the text input sucks. Tapping and swiping is fun, typing on keyboard sucks, it kills the fun. I'm not good at designing UIs, but I wonder if someone could think of a fun way of doing this... maybe some swiping, maybe a wheel that pops up if you hold the bolt and then you swipe how much you wanna tip...

**Comment by huumn** [comment]
kr suggested it just 10x's every bolt click. 1st click = 1 sat. 2nd click = 10 sat. 3rd click = 100 sat ... 

The problem is communicating this well is hard. I have a tipping tutorial now and people just dismiss it reflexively I've found.

**Comment by jnmclarty** [comment]
Might be fun to press and hold, measuring the hold duration.  Then use that in an exponentially growing formula.

The numbers could climb in a flashy/visible way.  Like you're shooting sats from your finger tips.  

You don't get fine control, because its just SO powerful.  It'd be like a little game to get the number you want.

Go in powers of 2, not 10.

Hold for...
* 200 ms -> 1 sat
* 400 ms -> 2 sats
* 600 ms -> 4 sats
* 800 ms -> 8 sats
* 1 sec -> 16 sats
* ...
* 2 sec -> 512 sats
* ...
* 3 sec -> 16,384 sats

You could interpolate that curve.  

A confirm-popup level could be set.  So, if you go past some number, it prompts you to confirm before actually sending.

**Comment by ludo237** [comment]
@jnmclarty no please it would be a nightmare for accessibility and mobile users

**Comment by huumn** [comment]
I personally like bolt.fun's interface for this (before they forced using WebLN). On SN, after the press and hold, we could have buttons for standard amounts: 10 sat, 100 sat, 1000 sat, 10000 sat.

**Comment by huumn** [comment]
We now have turbo tipping and autofill buttons on press and hold. More specific enhancements can be opened in a new issue.
