### ISSUE TITLE
Can't use "record video" as upload option on Safari iOS

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you click on Upload, you can upload an existing file or take a photo or video.

If you choose video, the resulting video can't be uploaded because it uses `.mov`.

### Screenshots

![signal-2024-11-10-162656](https://github.com/user-attachments/assets/8628ae2e-314d-4b30-96e1-4e2206da2117)

### Steps To Reproduce

1. Click on "upload file"
2. Select "Take Photo or Video"
3. Record video and try to upload

### Expected behavior

We support MOV format

### Device information

- OS: iOS
- Browser: Safari

**Comment by Soxasora** [comment]
I was tinkering with this issue and allowing `video/quicktime` mime type fixes it.
The real problem is that embedded mov files can only be seen by Apple users [per MDN](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#browser_compatibility). Transcoding to mp4 during the upload process could be an option though.

**Comment by huumn** [comment]
I was looking for something like [imgproxy](https://imgproxy.net/) for video awhile ago but I couldn't find anything.

Why aren't more people making stuff we need 😅

**Comment by Soxasora** [comment]
I could try to make a proof of concept with ffmpeg, this way not only SN could support mov files but also handle compression for all the other videos 🗜️
