### ISSUE TITLE
Image/link fee has `x` which makes it look like it's per image/link, and not a flat rate for posts with links or images

### ISSUE THREAD

**Issue by casey** [stackernews/stacker.news#188]
I noticed that my posting fee didn't go up when adding extra images and links, which is what I expected because of the `x` in front of the fee:

<img width="516" alt="Screen Shot 2022-08-19 at 11 53 42 AM" src="https://user-images.githubusercontent.com/1945/185687828-db981da1-d167-4b95-91c5-d69efc62bdac.png">

Maybe it should be a `+`?

**Comment by huumn** [comment]
It's a multiplier. So if your post fee is 100 sats, adding a link or images makes it cost 1000 sats.

If it were a plus, you'd be paying 11 sats rather than 10 sats.

Confusion noted though - it's definitely not per link/image. We are kind of still figuring out the best way to structure these fees and communicating them.

**Comment by casey** [comment]
Ah, gotcha. How about "image/link multiplier"? "fee" sounds like a fixed fee to me.

**Comment by huumn** [comment]
Yep, great idea!

**Comment by huumn** [comment]
We removed this entirely!
