### ISSUE TITLE
Support lightning address/lnurl-pay "descriptions"

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#230]

**Comment by cointastical** [comment]
This was again requested on an SN post:

*What about sending sats directly to a user in SN ?*
https://stacker.news/items/219912

**Comment by huumn** [comment]
> Or is this to surface descriptions when your SN wallet is funded, or both?

I think this is the one people ask for most. We have a minimal lightning address implementation and there's a lot more they can do. This is kind of the next thing we should add, but it be cool to fully feature the spec.

**Comment by SatsAllDay** [comment]
> > Or is this to surface descriptions when your SN wallet is funded, or both?
> 
> I think this is the one people ask for most. We have a minimal lightning address implementation and there's a lot more they can do. This is kind of the next thing we should add, but it be cool to fully feature the spec.

Cool. I will take a look at this issue, I'm interested in learning more about the lightning address spec and SN's implementation.

**Comment by SatsAllDay** [comment]
Doing some research...

[LUD-6](https://github.com/lnurl/luds/blob/luds/06.md) - where `payRequest` is specified, does not define a way for the payer to specify the description for the subsequently-generated invoice, so I think that would be left up to SN in our situation, which is what we're doing now with the hardcoded `Funding @ user on stacker.news` description.

[LUD-12](https://github.com/lnurl/luds/blob/luds/12.md) - where `comments` is specified, adds a way for the payee to allow comments on a `payRequest`. This is something that SN does not currently support, since we don't specify `commentsAllowed` in our response to `.well-known/lnurlp/[username]`. So, this is one feature we could implement.

However, the spec is not clear about _what to do_ with the comment. I think it's open-ended on purpose.

I think technically we could use the comment, if provided, as the description of the invoice that we generate in response to `GET /.well-known/lnurlp/[username]/pay?amount=<>&comment=<>`. I did find some [discussion](https://github.com/Dolu89/ligess/issues/10) that suggests this is a bad idea, so one alternative could be that we just alter our invoice table to store `comment` as a new field, and display it in the UI, but don't use it as the description of the invoice itself.

Thoughts?

**Comment by SatsAllDay** [comment]
I created #498 just to give us something to reference in further discussions. We don't have to keep any of it, but I thought it would be helpful to see what this might look like.

**Comment by huumn** [comment]
GIT MERGITH
