### ISSUE TITLE
Provide API 

### ISSUE THREAD

**Issue by abetusk** [stackernews/stacker.news#26]
Hacker News has an API to their data, providing an interface to query data from their site in JSON (see [here](https://github.com/HackerNews/API)). Hacker News provides it through `firebaseio`, so maybe it's worth pushing this to another service but the basic form would be something in the form of `https://stacker.news/items/1130.json?print=pretty` with the resulting `item` JSON closely mirroring the database schema.

Other tables in the database schema could be accessed similarly.

I do see an `api` directory so maybe this is already implemented? If so, it would be good to document. If not, then having an API so that other hackers can look at the data would be cool.

**Comment by huumn** [comment]
There's a graphql API that's effectively public but I have not documented it. Good rec!

**Comment by huumn** [comment]
Recently learned about LSATs. We could gate the API with [LSATs](https://docs.google.com/presentation/d/123tRENZY1tLz91iayu6AckD_2r3Ky1IWleX3bthcQv8/edit?usp=sharing) possibly and not need to have a rate limiting service - not that that's really a huge concern at this point.

**Comment by bitkarrot** [comment]
> There's a graphql API that's effectively public but I have not documented it. Good rec!

Does the graphql API let users post news as well? Would love to integrate this with my other media. Thanks for building this!

**Comment by huumn** [comment]
Posting news programmatically is going to be tricky ... because it'll make it trivial to create spam. AFAICT to start it'll be public read and on a case-by-case basis public write access. 

We'll see though.

**Comment by huumn** [comment]
> would paying sats to post be a deterrent b/c it would be too expensive to spam?
At 1 sat per post, no. At 1000 sats per post, probably.

**Comment by ekzyis** [comment]
This is a old ticket which looks like it could use some updated information.

> There's a graphql API that's effectively public but I have not documented it. Good rec!

There is https://stacker.news/api/graphql now with introspection enabled. This can be considered "documentation".

> Posting news programmatically is going to be tricky ... because it'll make it trivial to create spam. AFAICT to start it'll be public read and on a case-by-case basis public write access.
>
> We'll see though.

What we've seen is that someone just "reverse engineered" [0] the API which is used by the frontend and without asking for permission started to run a [Hacker News bot](https://stacker.news/hn).

_(Maybe this was written before we had escalating fees for spam.)_

So the API is usable, there are just no stability guarantees (we don't use [SemVer](https://semver.org/)) and there are no API keys (#670).

So my stance on this

> would paying sats to post be a deterrent b/c it would be too expensive to spam?
>
> At 1 sat per post, no. At 1000 sats per post, probably.

is that it will be non-trivial to enforce higher costs for "API usage" if we want to exclude frontend usage from these costs.

However, we do have some options:

- basic IP rate limiting: when rate limits are high enough, "normal users" will be excluded and only bots will get hit by them
- provide API keys for "honest users": if people don't have bad intentions, they would use API keys for easy access. We could then make them pay (more) if they create a lot of requests. So they could basically pay for more access. Since they are honest and use the API key (and thus don't try to hide), we can distinguish these requests from other requests.
- ...

[0] _The code is open source so I don't consider this to be reverse engineering._

**Comment by huumn** [comment]
closing as duplicate
