### ISSUE TITLE
Nostr login

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#334]
It's pretty trivial, but I keep forgetting to do this.

**Comment by ekzyis** [comment]
Do you have a specific NIP in mind? I only found [NIP-98](https://github.com/nostr-protocol/nips/blob/master/98.md) and an ongoing discussion here: https://github.com/nostr-protocol/nips/issues/154

NIP-98 also looks weird since there is no challenge involved. Only the window set by `created_at` seems to provide some 
(insufficient) protection against replay attacks :thinking:

**Comment by huumn** [comment]
I have an example in the outer space repo. I use a challenge+secret flow there, but a single challenge like we do here is fine.
