### ISSUE TITLE
Provide a way for users to switch between "compact" and "comfortable" views

### ISSUE THREAD

**Issue by brihuang99** [stackernews/stacker.news#369]
**Is your feature request related to a problem? Please describe.**
As a user, viewing stacker news  on my wide monitor can sometimes feel like I'm straining myself to digest the content because of how compact it can be.

**Describe the solution you'd like**
I think there can be benefits by providing different viewing modes, including a compact (default) view or a "comfortable" view where there are larger font sizes, padding, etc.

**Describe alternatives you've considered**
I suppose there could always be the consideration of making the sizes of the content more "adaptive" based on monitor width but that's just a lot of work. 

**Additional context**
Here's a screenshot from my monitor. For someone like me, I'd benefit from a greater sense of visual separation of the content. 
![Screenshot_20230729_105456](https://github.com/stackernews/stacker.news/assets/122472324/a81912ce-3128-4d9a-967e-fe2d971375a5)

I'm a UI/UX designer so I'd be happy to contribute any designs if needed!

**Comment by huumn** [comment]
In general our UX needs some help. Can you share your monitor size?

When I'm using a browser on a wide monitor, I usually won't have it be fullscreen but I can start trying to do it more and see if anything jumps out.

**Comment by ekzyis** [comment]
> As a user, viewing stacker news on my wide monitor can sometimes feel like I'm straining myself to digest the content because of how compact it can be.

I agree since I noticed a similar feeling regarding the width. It just never was enough of a problem to mention it and was not always in my mind. But thanks for creating the issue, now I can share my thoughts on this too, haha

For example, HN vs SN:

_front pages look similar clustered; HN has just more width which isn't used like SN. So both waste screen real estate:_

![2023-07-29-171738_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/0e650524-60c9-4564-b124-4b2b01ba8309)

![2023-07-29-171749_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/aed82996-5fe0-4fd4-9d14-b8b4d02ff369)

_however, in the comment section, HN makes great use of the width unlike SN:_

![2023-07-29-171841_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/0fcc0730-3b26-42b7-828f-87d162590603)

![2023-07-29-172317_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/d0c0f812-10bd-41f8-a000-431e4eae5277)

But I understand that you are are hinting at more then just the limited width:

> "comfortable" view where there are larger font sizes, padding, etc.

So it would require some testing if this can be done with only CSS media queries. I think the width can easily be changed by just adding another CSS media query rule.

**Comment by brihuang99** [comment]
> In general our UX needs some help. Can you share your monitor size?
> 
> When I'm using a browser on a wide monitor, I usually won't have it be fullscreen but I can start trying to do it more and see if anything jumps out.

My monitor size is 24 inches, resolution is 1920x1080. 

I'm pretty new to GitHub/Stacker News so I'd be happy to work on other UX issues. I can look at what's open but feel free to point me towards anything else that comes to mind

**Comment by huumn** [comment]
> however, in the comment section, HN makes great use of the width unlike SN:

While it might *look* like better use, lines of text that wide are harder to read. Afaik for ease of reading, ideal line width is <80 chars. Longer line width does reduce the vertical space taken up by any comment though.

**Comment by huumn** [comment]
Going to close as our view is fairly compact now and I'm not sure what an alternative view would look like.
