### ISSUE TITLE
[Feature request] See which/what users are upvoting

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#4]
Currently notifications just tell you you've stacked sats but you aren't told who upvoted you or which content got upvoted.

**Comment by jsarenik** [comment]
@huumn it may be desirable. Please keep anonymity of upvoting as an option (both for the author and the upvoter).

**Comment by huumn** [comment]
Can do! I think you're right too. I'll just tell the author what story was upvoted not who ... and maybe at some later date I'll give them the option to reveal their identity.

**Comment by abetusk** [comment]
Note that this is potentially fraught with problems. HN tries to resolve some of these issues by only revealing comment score to the author, along with other tricks depending on user Karma (see [HN undocumented](https://github.com/minimaxir/hacker-news-undocumented/blob/master/README.md#downvoting-comments)).

For small communities this isn't a problem at all but if the SN community ever gets larger, this could become an issue. SN is different in that users are effectively paying to upvote, which, from my completely uninformed position, seems like it would hugely disincentivize bad behavior and other spam. SN also doesn't have a downvote (as far as I can tell?) so a lot of the HN policies may be moot.

One more resource to be aware of is Clay Shirky's ["A Group Is Its Own Worst Enemy" (2003)](https://web.archive.org/web/20131130191257/http://www.shirky.com/writings/group_enemy.html) which talks about some things to accept and some things to potentially design for in a community. I know this issue is just about seeing which users are upvoting but, to me, it gets at the core of designing features for social websites.

I'm not sure I'm suggesting anything actionable and I hope I'm not detracting from the conversation. I was just hoping to provide some resources so whatever gets implemented or not has some more context.

**Comment by huumn** [comment]
That was all very helpful abetusk! All brain is energy is welcome. I only have so much of it myself. 😅

I think you're right that we could be creating issues at scale, but at this stage scale is not something we have to fear - I can always take away abused features but I can't as easily get early users back if they don't get enough value from the product. Still a worthy thing to have in the back of our minds so that we don't unintentionally build a bomb.

I'm going to read that Shirkly piece. He's a wizard.

Thanks again for the thoughtful thoughts.
