### ISSUE TITLE
Enable SN in Breez (with WebLN)

### ISSUE THREAD

**Issue by notnout** [stackernews/stacker.news#46]
WebLN is a pre-requisite for the app to be included in Breez and other lightning apps. 

The implementation can be fairly simple, https://webln.dev/#/ and when ready worth pinging some of the teams like Breez to include SN there.
This would be both useful and also good marketing ;)

**Comment by huumn** [comment]
We already have support for it on invoice/withdrawal. https://github.com/stackernews/stacker.news/issues/35 Is there some functionality I'm missing?

**Comment by notnout** [comment]
Then I guess the main missing point is sending PR to Breez to enable it there? :)

**Comment by huumn** [comment]
The current blocker is implementing this https://github.com/breez/breezmobile/wiki/Adding-a-WebLN-widget-with-LNURL-Auth ... unfortunately it requires me to implement a novel auth flow just for Breez .

(I wish they'd save credentials by just stashing browser cookies - it'd allow web apps to onboard without having to do anything new with regard to auth regardless of the way the app auths users because they likely all use cookies anyway.)

**Comment by huumn** [comment]
Note to self: To get this to work I'll have to create a server-side version of this function and then inspect the resulting cookies to grab the jwt https://github.com/nextauthjs/next-auth/blob/78fa33312f4d64b74e01ee479ba4faedf3980f71/src/client/index.js#L177-L238
