### ISSUE TITLE
Post pinning

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#61]
I want posts to be able to be pinned.

I mostly want this for a daily discussion thread, but if that's what we want there will need to be recurrence. Also, there's a question of whether pinning should be a mod only ability or anyone can pay to get a post pinned. 

It makes sense to give mods this ability, especially for recurrent pins. 

However, perhaps there can be a running auction for pinned posts that non-mods can initiate - basically an ad auction.

**Comment by ekzyis** [comment]
Reopening because it's a feature request by territory founders

**Comment by ekzyis** [comment]
> Cool. It'd be cool to give them recurring pins too while we're at it, but that's a nice to have if anything

To let them create their own saloons for example?

**Comment by huumn** [comment]
Yes!!

**Comment by ekzyis** [comment]
> Yes!!

Mhh, I wonder if there are other uses cases though. ~Wouldn't it~ I think it would make sense to just change the saloon code to give every sub a own saloon automatically with no founder interaction required.

Currently, the saloon shows up in every feed anyway.

However, since this could be a big sudden change and lead to confusion, we could instead allow founders to mark the saloon as "dedicated" or something. Then we overwrite the link to the global/public/<insert better word> with a link to a dedicated saloon.

At this point, it might make sense to just write code for a generic solution like repinning though.

**Comment by ekzyis** [comment]
> I would also like pinned comments for posts... but I'm expanding scope. I should open a feature request.

https://stacker.news/items/401153

**Comment by huumn** [comment]
Who gets to pin comments? The OP or the founder? I'm afraid of OPs doing this because there's precedent for "check out my soundcloud" type comments.

**Comment by ekzyis** [comment]
Founders can pin posts, OPs can pin replies to their post

**Comment by huumn** [comment]
Yeah all good. I just wanted to inject some nuance into use/abuse cases.

We can always remove it if it's abused. I think for comment sections we might solve the "append" case by modifying ranking to favor OP/FWD_STACKERS, but that's a bigger lift probably.

**Comment by ekzyis** [comment]
I think 

> - ~[ux] allow pinned items to get zapped (requesting for comments, optional)~ _MVP feature creep, let's get some user feedback first_

was a bad decision. How zapping on pinned items wasn't obvious to me but I will just allow zapping by clicking the pin (for now?). PR should be up in a bit.
