### ISSUE TITLE
Receiving push notifications even after logging out of the site

### ISSUE THREAD

**Issue by felipebueno** [stackernews/stacker.news#625]
I keep receiving push notifications on my phone even after logging out of the site.

EDIT: I know I could login and disable notifications in the settings page but that should not be necessary because I do want to receive notifications on my other devices.

![image](https://github.com/stackernews/stacker.news/assets/241271/677e5c15-0690-4ba5-af2d-b11c0435950f)

![image](https://github.com/stackernews/stacker.news/assets/241271/bfb62eda-9aa6-4cf9-978e-7d3a137635bd)

**Comment by ekzyis** [comment]
> EDIT: I know I could login and disable notifications in the settings page but that should not be necessary because I do want to receive notifications on my other devices.

This is a setting per device, so you won't lose push notifications on other devices if you disable it on one device. You should have enabled them one by one per device.

But still receiving push notifications without a session is definitely not expected behavior. Makes sense that it happens, but I agree with you, this shouldn't happen.

**Comment by huumn** [comment]
Maybe we should delete the push subscription when stackers logout on devices?

**Comment by ekzyis** [comment]
Thought about if we should resubscribe them automatically if they login again. 

But then we have to add some logic _again_ to determine if they were subscribed when they logged out etc.

So I decided to not do this and first gather some real life user experience.
