### ISSUE TITLE
Quote replies not working

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#639]

**Comment by ekzyis** [comment]
https://github.com/stackernews/stacker.news/assets/27162016/a7677921-8933-4110-a035-aa836c24045e

**Comment by huumn** [comment]
Ah thanks, yeah it appears to be a problem only when it isn't open yet.

**Comment by ekzyis** [comment]
I think there was always a race condition since the input we want to reference does not exist yet (`d-none`) when we click "quote reply" but it is opened using `setReply(true)` in `quoteReply`.

_input only rendered if `tab === 'write'`:_
https://github.com/stackernews/stacker.news/blob/589b15b597980cf9eab2904a2a7df6284418971c/components/form.js#L314-L321

_render input using `setReply(true)`_:
https://github.com/stackernews/stacker.news/blob/589b15b597980cf9eab2904a2a7df6284418971c/components/reply.js#L74

I think it used to work since the code that opened the reply used to run faster so at the time this line was hit:

https://github.com/stackernews/stacker.news/blob/589b15b597980cf9eab2904a2a7df6284418971c/components/reply.js#L90

the refs already exist. But this is no longer the case.

I verified this by using `await sleep(1000)` after `setReply(true)`:


https://github.com/stackernews/stacker.news/assets/27162016/9477427e-6e7a-4a42-8ecc-30711939da98

**Comment by huumn** [comment]
I think it might be some other change I made to reply recently. I noticed we were rendering the markdown text field for every place there might be a reply but `d-none`ing it ... so instead I conditionally rendered it.

So I think you're right, it's just not open when the quote reply runs. I'd still like to avoid rendering so maybe we can do a setTimeout on the quote reply for like 100ms

**Comment by ekzyis** [comment]
> I'd still like to avoid rendering so maybe we can do a setTimeout on the quote reply for like 100ms

or we could poll every 50ms for the refs to be defined: use `setInterval` and reschedule if they aren't defined yet.

Then it's not a race condition anymore, just unelegant code, haha

**Comment by huumn** [comment]
I haven't looked at the code but I imagine that won't be necessary

**Comment by ekzyis** [comment]
A 100ms timeout is probably going to work, too, but my concern is only how reliable that is going to be in the long run
