### ISSUE TITLE
Don't pay existing invoices already paid

### ISSUE THREAD

**Issue by TonyGiorgio** [stackernews/stacker.news#720]
I've lost a few hundred sats due to accidentally using the autofill option instead of paste option on my phone.

I'd suggest these two things: 

1. Turn off auto fill on the withdraw page. I believe HTML form attributes make this easy.
2. Lookup the invoice before attempting to pay it, fail the withdraw call if already paid. 

I'm unsure if the payments were swiped by SN or by another node on the network (possibly by our Mutiny LSP).

**Comment by ekzyis** [comment]
> Lookup the invoice before attempting to pay it, fail the withdraw call if already paid.

You're talking about invoices that weren't created by SN, right?

Since for invoices created by SN, we already do this by checking if the withdrawal invoice already exists in our database before paying it:

https://github.com/stackernews/stacker.news/blob/9698679d381e4706348c0c2263bb36090f03a01b/api/resolvers/wallet.js#L476-L486

If we've already seen this invoice, the database will respond with an error. See this video:

<details>

<summary>video</summary>

https://github.com/stackernews/stacker.news/assets/27162016/028588df-2691-4956-9984-92348c767f43

</details>

Nonetheless, I am struggling to understand how paying the same invoice twice leads to a loss of funds. I definitely did not know that this might be a problem, so thanks for bringing this up! If you don't mind, can you elaborate on this?


> Turn off auto fill on the withdraw page. I believe HTML form attributes make this easy.

But I agree, auto fill on this input doesn't make sense:

![2023-12-29-234019_753x354_scrot](https://github.com/stackernews/stacker.news/assets/27162016/fdf78055-6fd2-4c4e-a90c-c4947c059dc6)

**Comment by TonyGiorgio** [comment]
Preimages are revealed to node routers when an invoice is paid. If they see the same payment being routed again with the same prrimage, they can swipe the funds. 

I know for a fact that SN let me withdraw to the same invoice multiple times, so perhaps the logic for preventing that isn't working.

**Comment by ekzyis** [comment]
> Preimages are revealed to node routers when an invoice is paid. If they see the same payment being routed again with the same prrimage, they can swipe the funds.

Ah, makes sense. Forgot that the preimages must be kept secret until the channels are closed - not until the payment is done.

> I know for a fact that SN let me withdraw to the same invoice multiple times, so perhaps the logic for preventing that isn't working.

Just tried this on https://stacker.news/ with a Phoenix invoice. Same error when trying to withdraw to the same invoice again.

Let's wait for @huumn on this then, maybe he knows more. He also can lookup stuff in the LN node if that helps.

**Comment by huumn** [comment]
I suspect tony is deleting his invoices so we can't throw this error.

We should however prevent autofilling.

**Comment by ekzyis** [comment]
> We should however prevent autofilling.

Done in #721

**Comment by TonyGiorgio** [comment]
> I suspect tony is deleting his invoices so we can't throw this error.

Ah, yeah I have auto delete turned on. Interesting. Is it deleted on the LND side as well? I didn't think LND would allow paying an invoice twice.

**Comment by huumn** [comment]
> Is it deleted on the LND side as well?

It isn't but we an issue up for doing that too. 

> I didn't think LND would allow paying an invoice twice.

Same. I've definitely seen it throw `invoice already paid` messages before.
