### ISSUE TITLE
No notification for @delete usage in post

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#728]
**Description**

Stackers don't get notifications if they use the built-in delete bot on posts. The post is still successfully deleted though.

**Steps to Reproduce**

Mention `@delete` in a post

**Expected behavior**

Receive notification that it worked.

**Comment by ekzyis** [comment]
Mhh, just tested this. Got a notification for link and discussion posts.

**Comment by ekzyis** [comment]
Ok, I think the bug is in this line:

https://github.com/stackernews/stacker.news/blob/562b243111c23df7201ce112a72b6f9a62d0f4cf/lib/form.js#L18

I don't know what this line does in prod (since it works locally) but this doesn't seem right to me.

**Comment by ekzyis** [comment]
Mhh, still doesn't work

**Comment by SatsAllDay** [comment]
I am debugging this one [here](https://stacker.news/items/511890)

I suspect the issue is on [this line](https://github.com/stackernews/stacker.news/blob/d7ecbbae3a86ac62d3ad30f5affa8d240c722ce0/components/toast.js#L113), where toasts are being removed due to the page navigation that happens when you create or edit a post.

**Comment by SatsAllDay** [comment]
To be clear, I'll introduce a new flag, like `persistOnNav` to handle this case, since this isn't a cancelable event
