### ISSUE TITLE
Feature: Allow connecting self hosted LN wallets / nodes with SN

### ISSUE THREAD

**Issue by notnout** [stackernews/stacker.news#75]
This is potentially a longer term feature, but it would help decentralization if it would be possible to use self-hosted wallet or even a node with SN. 

Example 1: make it possible to use Alby to vote with sats or receive sats directly into Alby. I'm not sure if there's a good protocol to do this already.  
Example 2: podcasters that register in podcastindex.org provide node id and that lets them receive the streaming sats. It would be great if they could get SN sats using the the same id.

**Comment by huumn** [comment]
I'm chatting with the Alby folks about this. There's also lightning node connect which should simplify this more. To the extent that I've thought about this ...

1. The UX around this stuff is still tricky
2. Unless you have a channel open with SN, it'll probably cost more than 1 sat to perform 1 sat actions because of routing fees

Giving the users the option, even if they don't use it, is probably a win though.

**Comment by notnout** [comment]
Agreed that having the option is a win even if it's not the most used feature. 
This will also be valuable if you are considering to eventually create a federated model (like ActivityPub) or maybe even fully decentralized where users fully own their value and their data...
