### ISSUE TITLE
Make NWC zaps more responsive

### ISSUE THREAD

**Issue by benthecarman** [stackernews/stacker.news#858]
I keep accidentally double zapping posts because it doesn't provide immediate feedback when I click the lightning bolt. Would be nice if it went to a pending state immediately so I'd know that I did click it

**Comment by ekzyis** [comment]
I believe most latency comes from attempting to pay from the custodial wallet first so maybe [this line](https://github.com/stackernews/stacker.news/pull/857/files#diff-00f337183418936435f48bbe59c72903633a7edb34bca37f6002c467362531a8R314) (already throwing the error on the client instead of waiting for a server response) in #857 might already help but I will check. Thanks for the feedback!

**Comment by benthecarman** [comment]
> I believe most latency comes from attempting to pay from the custodial wallet first

My balance is displayed so you should have this locally and should be able to tell if it will work or not

**Comment by ekzyis** [comment]
> My balance is displayed so you should have this locally and should be able to tell if it will work or not

Yeah, that's what I am doing with the line I was referring to in #857.

**Comment by huumn** [comment]
This was fixed awhile ago.
