### ISSUE TITLE
OP Pinned Comment

### ISSUE THREAD

**Issue by dillon-co** [stackernews/stacker.news#892]
**Is your feature request related to a problem? Please describe.**
I recently made a post and realized after it was too late that I got something wrong. I commented the edit but that's been moved down into the middle of the comments

**Describe the solution you'd like**
It would be nice to add an edit / update to a post that doesn't change the original post so if a poster makes a mistake they don't have to keep pointing to the comment that explains the correction

**Describe alternatives you've considered**
a comment that's pinned to the top or and `add edit/update` button that appends an edit to the post with -EDIT at the beginning, like you see on reddit sometimes

**Additional context**
I gave a faulty analogy of bitcoin mining and I'm scared of bitcoiners rage lol

**Comment by ekzyis** [comment]
> a comment that's pinned to the top

You can pin comments if you are the OP like I did [here](https://stacker.news/items/436752):

![2024-03-01-182632_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/9d66ebd1-9211-49f1-80f9-b676adb00f29)

We used to have #121 for this but it was closed because pinned comments solve the same use case
