### ISSUE TITLE
Image Carousel / Slideshow

### ISSUE THREAD

**Issue by felipebueno** [stackernews/stacker.news#986]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem, just an UX improvement

**Describe the solution you'd like**
When zooming an image, allow the user to slide/swipe through the other images of that post or comment

**Describe alternatives you've considered**
Closing the zoomed in image and clicking/tapping the next one 

**Additional context**
It would be much easier to navigate through the images of [this](https://stacker.news/items/484362) post, for example

![image](https://github.com/stackernews/stacker.news/assets/241271/ca681264-b8b5-4c61-a62e-9bbd511e3f85)

**Comment by ekzyis** [comment]
I discussed something similar with [@Natalia](https://stacker.news/Natalia):

She mentioned that she would like to upload multiple images at once and then all images would show up as one image (a collage of them) and clicking on it would trigger a slideshow.

Currently, she edits multiple images into a collage herself [like in this post](https://stacker.news/items/484127). If she doesn't do this, the layout of her post gets destroyed by too many images.

_Just wanted to mention this here. Having a slide show for individual images would be the first step before we create collages. For collages, some things aren't clear yet anyway like how opting out of them should work. I don't think you always want to create a collage just because you uploaded multiple images at once._

**Comment by felipebueno** [comment]
> Having a slide show for individual images would be the first step before we create collages
> ...
>  I don't think you always want to create a collage just because you uploaded multiple images at once

Yeah, I think those are separate features too

**Comment by huumn** [comment]
I think if you upload multiple images we put them into a markdown table for you.

**Comment by felipebueno** [comment]
That would be nice too but I think the slideshow/carousel thing would still be useful for when we tap or click an image to zoom. Then we would be able to swipe through the other images without needing to close the current zoomed in one

**Comment by huumn** [comment]
You're right, carousel on click would be cool and collaging is a distinct issue.

**Comment by felipebueno** [comment]
I was going to work on #943 but I think it's too advanced yet for my little time and little knowledge of the codebase.

I think this one would be a simple enough feature to start with. @huumn Can I (or you) assign it to me?

**Comment by huumn** [comment]
@felipebueno you should be able to assign yourself to stuff - you have triage perms.

**Comment by felipebueno** [comment]
I know, I was just making sure nobody else was working on that already :grin: 

For the next issues, I'll consider it "vacant" if it's not assigned to anyone :slightly_smiling_face: :+1:

**Comment by felipebueno** [comment]
cooking... :)
